AxisCommunications/acap-rs

.github/dependabot.yml
Group dependency updates to reduce noise from pull requests. Major and security updates are left grouped so that they can be given careful and, in the case of security updates,  expedited consideration.
Set the versioning strategy to "lockfile-only" because the default value, presumably "auto", would bump the required version of dependencies in the manifest(s) and in turn force these requirements onto our users.
One downside of this is that dependabot will not attempt to "widen" the versions specified in the manifest(s), which means we may forget to add support for new major versions. But as of writing the "cargo" package-ecosystem supports only "auto" and "lockfile-only".
=> Set dependabot group and versioning-strategy

.dockerignore, Dockerfile, Makefile, README.md, docker/install_rust.sh
This should make it easier to build the example apps in CI systems
where setting up docker-in-docker is difficult. As desirable side
effect of this is that it becomes easier to build the example apps on
any system, including those where following the advanced setup may be
difficult.
To be able to build both inside and outside docker containers branching
is introduced in the makefile. The added complexity is unfortunate but
worthwhile in order to better support containerized builds. The goal is
to eventually replace most of the `Makefile` with a cargo plugin.
=> Demonstrate containerized builds

Makefile
The new "docstrings" don't add much information, but they make it easier comparing the `Makefile` in this project to that in acap-rs-app-template because the diff is smaller and they only differ where there is a good reason for doing so.
Also add and remove some newlines; double newlines only precede sections to make them easier to spot.
=> chore: Explain more make targets

Makefile
At some point, probably when resolving a merge conflict, several targets stopped working as intended. There needs to be a more structured way of running all tests, but I don't want to invest in that before I start integrating the new build tool.
=> fix: Repair `Makefile`

README.md
This will be less important once dev containers are fully adopted but we may as well document dependencies as clearly as possible.
Resolves #12
=> Document `python3-venv` dependency

README.md
The intention of this link and the corresponding link in the other repo is to help potential users and contributors find the repo that is most suitable for what they want to do.
=> Add link to acap-rs-app-template in `README.md`

.devcontainer/devcontainer-lock.json, .devcontainer/devcontainer.json, .github/dependabot.yml, Dockerfile, README.md
`devcontainer-lock.json` is created like:
`devcontainer build --workspace-path . --experimental-lockfile`
In `devcontainer.json`:
- `name` is set to match the name of this project because that seems like a reasonable way to help users understand what context they are working in.
- `build` is set to use the existing `Dockerfile`
- `features` is set to use `common-utils` because this seems to be required to get `remoteUser` to work.
- `remoteUser` is set to the local user because without it files created are owned by root. This surprises me because from the docs I got the impression that dev containers would ensure permissions are mapped in a sensible way by default.
- `containerEnv` is set to overwrite `CARGO_HOME` because it is set in the image causing `cargo` to use a directory that is …
=> Add dev container

Makefile, README.md
I rarely find myself wanting to build for targets other than the device that I am currently testing with, and having to wait twice as long as necessary is annoying.
I expect that CI workflows will still want to build for multiple targets, but that it should be a relatively small effort to call make twice since the developer only has to write that code once.
A side effect of this change is that CI now only builds apps other than `hello_world` for one target. This could easily be fixed by adding a couple of lines in `CI.yml` but I think this is probably desirable since I expect the compilation success to be highly correlated.
=> Make the `build` verb build for only one target

Cargo.lock, Cargo.toml, apps/consume_analytics_metadata/Cargo.toml, apps/consume_analytics_metadata/src/main.rs, apps/hello_world/Cargo.toml, apps/hello_world/src/main.rs, apps/licensekey_handler/Cargo.toml, apps/licensekey_handler/src/main.rs, crates/acap-logging/Cargo.toml, crates/acap-logging/README.md, crates/acap-logging/src/lib.rs, crates/app-logging/Cargo.toml
The package is renamed to `acap-logging` to communicate that it is meant for logging in ACAP apps as opposed to apps in general.
=> chore: Prepare logging library crate for publishing

Cargo.lock, README.md, apps/hello_world/src/main.rs, crates/acap-logging/Cargo.toml, crates/acap-logging/README.md, crates/acap-logging/src/lib.rs
The crate level documentation is taken from `README.md` to make it easier to ensure that crates.io, docs.rs and GitHub all show sensible documentation with minimal effort.
Also update the `hello_world` example since it would not display any output by default when run in a terminal. To increase the utility of the app a bit further without increasing the complexity it is used to also demonstrate the effect of logging at other levels and of printing.
=> Improve acap-logging docs

Makefile
Running clippy with `RUSTFLAGS` set invalidates the cache from cargo invocations without it.
Before:
- Cold: 815,41s user 105,52s system 525% cpu 2:55,18 total
- Warm: 458,08s user  64,10s system 417% cpu 2:05,20 total
After:
- Cold: 652,06s user 81,11s system 459% cpu 2:39,48 total
- Warm:  26,31s user  1,93s system 109% cpu   25,76 total
The remaining time seems to be dominated by producing the `.eap` files; running `cargo-acap-build` takes 23s. This is in large part driven by the size of the executables because if the profile is changed to release the total size of the files that need to be packed drop from 211M to 53M and the time drops to 6s. But I suspect not all of it can be attributed to `tar` because doing that manually takes only 8s and 2s, respectively, leaving most of the time …
=> fix: Deny lint warnings without `RUSTFLAGS`

.devhost/install-system-packages.sh, .devhost/install-venv.sh, .dockerignore, Cargo.lock, Makefile, crates/acap-vapix/src/apis.rs, crates/acap-vapix/src/apis/parameter_management.rs, crates/acap-vapix/src/http.rs, crates/acap-vapix/src/lib.rs, crates/device-manager/Cargo.toml, crates/device-manager/README.md, crates/device-manager/src/initialization.rs, crates/device-manager/src/lib.rs, crates/device-manager/src/main.rs, crates/device-manager/src/restoration.rs, crates/device-manager/src/vapix.rs, crates/device-manager/src/vapix/ajr.rs, crates/device-manager/src/vapix/ajr_http.rs, crates/device-manager/src/vapix/axis_cgi.rs, crates/device-manager/src/vapix/axis_cgi/featureflag1.rs, crates/device-manager/src/vapix/axis_cgi/firmwaremanagement1.rs, crates/device-manager/src/vapix/axis_cgi/pwdgrp.rs, crates/device-manager/src/vapix/axis_cgi/pwdgrp/add_10_12_initial_response.html, crates/device-manager/src/vapix/config.rs, crates/device-manager/src/vapix/config/ssh1.rs
Being able to quickly restore a device to a known baseline makes it easier for me to do rigorous testing; removing apps manually is a hassle and may not be enough to undo the effects that development has had on a device either because I changed some setting or because an app did.
The variant of VAPIX used has diverged from that which was integrated as its own crate. Notable differences include:
- `acap-vapix` uses builder style public interfaces. These are closer to what I expect the final result will look like since they allow greater flexibility in use and evolution.
- `acap-vapix` draws the line between request and client in a way that gives the APIs less control over things like headers. This is better aligned with how many APIs since they are ignorant of headers, including …
=> feat: Add `device-manager` bin and lib crate

crates/acap-vapix/src/lib.rs, crates/device-manager/src/initialization.rs, crates/device-manager/src/main.rs
With this change it is possible to compile an app for host and run it without modifications, provided that:
- The necessary environment variables are set.
- The device is configured accordingly, and with the authentication policy set to basic.
In `crates/acap-vapix/src/lib.rs`:
- Include both code paths at compilation time because also making imports conditional to satisfy the linter is annoying. The two reasons I can think of to not do this are:
- The compiler is not able to optimize away the unused path making the binary bigger (I don't know if this is the case, but so far I am not tackling binary sizes).
- One branch has dependencies that the other does not (not the case here since both branches depend on `anyhow` and `std`).
In `crates/device-manager/src/main.rs`:
- Set the …
=> feat(acap-vapix): Create client from env on host

Makefile, apps/vapix_access/src/main.rs, crates/acap-ssh-utils/src/lib.rs, crates/acap-ssh-utils/src/main.rs, crates/acap-vapix/README.md, crates/acap-vapix/src/ajr.rs, crates/acap-vapix/src/ajr2.rs, crates/acap-vapix/src/ajr_http2.rs, crates/acap-vapix/src/apis.rs, crates/acap-vapix/src/apis/basic_device_info.rs, crates/acap-vapix/src/apis/basic_device_info/get_all_unrestricted_properties_10_12_initial_response.json, crates/acap-vapix/src/lib.rs
`Makefile`:
- Set `--test-threads=1` when running tests on target because oftentimes these tests will be using scarce resources in which case running them in parallel may result in consistent or sporadic failures. In this case it seems that when a second test requests credentials using the same name (I have not tested using different names), either the old or the old credentials are invalidated causing the test to because of HTTP status code 401.
`crates/acap-ssh-utils/src/lib.rs`:
- Add `args` argument primarily to allow setting `--test-threads` when running tests.
`crates/acap-vapix/src/ajr_http.rs`:
- This function was originally split to make it usable from basic device info, which uses a request that cannot be serialized with the existing envelope model. I kept the split after moving …
=> feat(acap-vapix): Add basic device information API

Makefile
Essentially any target that uses `cargo-acap-build` needs this prerequisite because it will try to use `acap-build` which fails if there is no `LICENSE` file.
The cause of it being omitted is probably that I didn't think enough about which targets needed it and since `make build` usually precedes `make run` and `make test` without cleaning the repository between, these targets appeared to work.
=> fix: Add prerequisites and update docstrings

README.md
This is already documented in the template but I either forgot or decided not to document it here. Since this is the second time the problem is reported and there probably aren't many users in total, it is probably a good idea to rewrite the `Dockerfile` such that it can handle CR LF.
=> chore: Add troubleshooting section

.devhost/install-venv.sh, Cargo.lock, Makefile, apps/consume_analytics_metadata/src/main.rs, crates/cargo-acap-build/src/cargo_acap.rs, crates/cargo-acap-build/src/lib.rs, crates/cargo-acap-build/src/main.rs, crates/cargo-acap-sdk/Cargo.toml, crates/cargo-acap-sdk/README.md, crates/cargo-acap-sdk/src/command_utils.rs, crates/cargo-acap-sdk/src/commands.rs, crates/cargo-acap-sdk/src/commands/build_command.rs, crates/cargo-acap-sdk/src/commands/completions_command.rs, crates/cargo-acap-sdk/src/commands/install_command.rs, crates/cargo-acap-sdk/src/commands/run_command.rs, crates/cargo-acap-sdk/src/commands/test_command.rs, crates/cargo-acap-sdk/src/main.rs
`crates/cargo-acap-build/`:
- Rewrite to make app/package name of artifacts available to users. This is needed to reliably install, patch and run apps built in test mode without inspecting the EAP or parsing the name of the EAP file.
- Replace the big-function interface with a builder style interface to make it easier to use with optional arguments and to decrease the probability of future additions being breaking changes. It is done in this commit since the API is broken anyway.
- Add artifact dir option to avoid duplicating the `copy_eaps` logic in `cargo-acap-sdk`. Duplication is not always bad but since Cargo is getting the same feature, it seems reasonable that our API which we want to be similar to Cargo's should get it too. Note that this used to be known as `--out-dir` in Cargo. …
=> feat!: Add cargo-acap-sdk tool

Makefile
`Makefile`:
- `ACAP_BUILD` is unused.
- `run` and `test` no longer forwards environment variables.
- Putting `--` on its own line makes it easier to see what is passed as arguments and what is passed as values.
=> Tidy up in `Makefile`

Cargo.lock, Makefile, crates/acap-vapix/src/apis/basic_device_info.rs, crates/acap-vapix/src/http.rs, crates/cargo-acap-build/src/cargo_acap.rs, crates/cargo-acap-sdk/Cargo.toml, crates/cargo-acap-sdk/src/commands/build_command.rs, crates/cargo-acap-sdk/src/commands/install_command.rs, crates/cargo-acap-sdk/src/commands/run_command.rs, crates/cargo-acap-sdk/src/commands/test_command.rs, crates/cargo-acap-sdk/src/main.rs, crates/device-manager/src/restoration.rs
This has two benefits:
- users don't need to remember or look up the architecture of the device being targeted.
- users don't have to specify the architecture. This is especially helpful when switching between devices frequently.
`crates/acap-vapix/src/apis/basic_device_info.rs`:
- Document my experience using the API to help me remember what to look out for when I address the TODO. It would probably be better to do this in an issue, but I think having a lot of issues could discourage potential contributors from interacting.
`crates/cargo-acap-build/src/cargo_acap.rs`:
- Add more context because learning that an expected file does not exist in `None` does not provide much information about how to resolve the problem.
`crates/cargo-acap-sdk/Cargo.toml`:
- Use same version of `tokio` as …
=> feat(cargo-acap-sdk): Fetch target from device

Cargo.lock, crates/cargo-acap-sdk/Cargo.toml
I do this not because the state of the tool has crossed some threshold, but because it is being used and having versions makes it easier for users to install and it makes it easier to talk about which version is being used or when things change.
I do not plan to publish this version because I am still unsure about the name.
=> chore: release cargo-acap-sdk 0.1.0

.devhost/install-venv.sh
This is easy to do, but it took me a long time to get around to it and I hope having it set out of the box will help others adopt the practice faster. For me, having it set automatically in new shells is a nice convenience.
On my system I have to type car^I-ac^I-s^I to complete `cargo-acap-sdk` which is rather annoying, asdk is both shorter and requires fewer finger movements on the keyboard.
`.devhost/install-venv.sh`:
- Using `$0` instead of `$(basename $SHELL)` seems easier, but it resolves to the name of the script being sourced, not the name of the current shell.
=> Alias cargo-acap-sdk and enable completions

.devhost/constraints.txt, .devhost/install-venv.sh, .devhost/requirements.txt, Makefile
Intended benefits include:
- Faster (`make help` goes from 80ms to 3ms)
- One step closer to having no Python dependencies (While it would be nice to remove the virtual environment I still think Python can have a place in Rust ACAP app development, especially for tests and misc. scripts).
One downside is that the Rust implementation is not compatible with my `kindly` program that provides enhanced tab completions for `Makefile`s, but I wasn't going to push that onto `acap-rs` users anyway.
I admit that the utility of this tool is pretty low, and it could probably be removed, but it gives me joy so as long as it does not get in the way for someone else I will keep it.
=> chore: use Rust implementation of mkhelp

.github/dependabot.yml
Since the project does not host any applications that are deployed into exposed environments (the example apps are used as tests, and the other binary crates are development tools that typically don't listen on any ports, typically operate on trusted input or at least on a somewhat trustworthy network), I the downsides of frequent changes outweigh the benefits as I see it.
Benefits of weekly interval:
- Quicker response to potential security threats.
Benefits of monthly interval:
- Less maintenance.
- Better signal-to-noise ratio in the commit log.
=> chore: increase dependabot interval

Makefile
Prompted by me overwriting dependabot's updates to the lock file several times when it was inconsistent with the update was inconsistent with the manifest file.
This change should also improve reproducibility in general.
=> Use `cargo` with `--locked` option in checks

Cargo.toml, Makefile, crates/cargo-acap-sdk/src/commands/install_command.rs
The primary benefit is a smaller footprint on target; The total size of all EAP files as reported by `du` is:
- 15.0M before
-  4.4M after
The total size of all apps on target as reported by `du` is:
- 45.9M before
-  7.8M after
The free space on target as reported by `df` is:
- 24.8M before
-  6.7M after
(Tested with AXIS OS 11.11.73 on P8815-2)
I'm not entirely sure what to make of the discrepancy between the decreased footprint and the to a lesser extent increased free space; I suspect the compressed file system has something to do with it.
`Cargo.toml`:
- Customizing the release profile would be easier e.g. because that is the profile used by `cargo-acap-sdk install` by default. But since this project also hosts other binaries, such as `cargo-acap-sdk` I want to leave the release …
=> chore: Build apps with custom profile

Makefile
Without this, updating `Cargo.lock` in a way that is incompatible with the manifest files would not cause CI to fail, despite the use of the `--locked` option.
My theory is that when `cargo-acap-build` is invoked, directly from the `Makefile` or indirectly via `cargo-acap-sdk`, it uses `cargo metadata` which updates the lockfile, causing later `cargo` invocations to succeed even when using the `--locked` option.
Disproved theories include:
- The `cargo install` commands in `install-venv.sh` update the lockfile (checking the diff immediately after this step reveals no diff)
- Some other action, prior to `make check_all` update the lockfile (checking the diff immediately before this step reveals no diff)
`Makefile`:
- Use `cargo metadata` because it reconciles the lockfile without updating …
=> Add `Cargo.lock` to generated files

Cargo.lock, crates/cargo-acap-sdk/Cargo.toml
Changes since 0.1.0 include:
- Adds `start`, `restart`, `stop`, and `remove` commands that do what they say for the selected app(s).
=> chore: release cargo-acap-sdk 0.2.0

.devhost/install-venv.sh
This should have been done already in #62, but I forgot.
Also set the `--locked` option to improve reproducibility in theory; In practice I have not observed any problems, not even when it was a main suspect in #93.
=> fix: Install `cargo-acap-sdk` in venv

Makefile, apps-aarch64.filesize
Because this is an important property and we want to make sure that the size actually decreases when we make improvements and that it does not inadvertently increase.
The total size of all apps can be reported like:
```console
$ cat apps-aarch64.filesize | cut -f1 | paste -sd+ | bc
66644
```
Using `--profile app` would make the size smaller and, arguably, more representative but it would also require us to change what we build so it is skipped for now:
```console
$ cat apps-aarch64.filesize | cut -f1 | paste -sd+ | bc
4676
```
`Makefile`:
- Don't use the `--total` option to reduce the risk of merge conflicts.
- Don't use the `--human-readable` option to make it easier to sum the numbers afterwards.
=> chore: Track size of apps

crates/acap-ssh-utils/src/main.rs
With this change the help text becomes:
```console
$ acap-ssh-utils help
Utilities for interacting with Axis devices over SSH.
The commands assume that the user has already
- installed `scp`, `ssh` and `sshpass`,
- added the device to the `known_hosts` file,
- enabled SSH on the device,
- configured the SSH user with a password and the necessary permissions, and
- installed any apps that will be impersonated.
Neither the ability to patch an already installed app using SSH nor to run an installed app
with stdout attached to the terminal are officially supported use cases. As such all commands
provided by this program may stop working on future versions AXIS OS.
Usage: acap-ssh-utils --host <HOST> --user <USER> --pass <PASS> <COMMAND>
Commands:
patch      Patch app on device
run-app    Run …
```
=> fix(acap-ssh-utils): Warn users that commands may break

crates/device-manager/src/initialization.rs
For development, it is not feasible to sign the ACAP for every iteration.
Allow unsigned ACAPs as part of the initialization process.
=> feat(device-manager): Allow unsigned ACAPs

.devhost/install-devcontainer.sh, .devhost/install-venv.sh
The method I used for installing `npm` was flaky and a common source of false positives in CI. Since it is not needed in CI, and it is needed locally only when not using the recommended dev container based environment, not installing it by default seems like a cost effective remedy.
The steps to install it are still kept to make it easier to reproduce my development environment. It expects that a `venv` is already `source`d but does not eagerly verify this. Since it doesn't look like it has any bad side effects and the script will be used only rarely and is not easily discoverable this feels like a worthwhile trade-off.
=> Don't install the `devcontainer` program by default

Makefile, crates/cargo-acap-build/src/main.rs
Since `cargo-acap-sdk` is the preferred tool for local development it should be relatively rare for people to use `cargo-acap-build` locally. As such it makes sense to optimize it for the continuous integration where I expect it will be used relatively frequently.
This decision rests on the assumption that there are few cases when a developer would be better server by `cargo-acap-build` for local development compared to `cargo-acap-sdk build`.
`Makefile`:
- Update targets to do the same as they did before.
`crates/cargo-acap-build/src/main.rs`:
- The pattern for overriding the profile is taken from `cargo-acap-sdk`.
=> feat!(cargo-acap-build): Make the release profile the default

Makefile
It took me a while to figure out that the reason my builds were failing on my renamed fork was because the working directory changed with the name of the repository. I hope that documenting these pitfalls will save time for others who might otherwise encounter and be confused by the same problems.
A couple of factors caused this to be especially confusing for me:
- The commit I was testing also affected the checksums.
- I was troubleshooting both on a renamed fork and a fork with the original name.
=> chore: Document pitfall with reproducible builds

Cargo.lock, Cargo.toml, crates/acap-ssh-utils/Cargo.toml, crates/acap-ssh-utils/src/main.rs, crates/cargo-acap-build/Cargo.toml, crates/cargo-acap-build/src/main.rs, crates/cargo-acap-sdk/Cargo.toml, crates/cargo-acap-sdk/src/main.rs, crates/cli-version/Cargo.toml, crates/cli-version/src/lib.rs, crates/device-manager/Cargo.toml, crates/device-manager/src/main.rs, crates/fleet-manager/Cargo.toml, crates/fleet-manager/src/main.rs
The goal is to make it possible for users to communicate what version
of the programs they are using when they experience issues.
`crates/cli-version/src/lib.rs`:
- Never fail because I want to avoid new users first experience being that the tools fail to install at all costs.
=> feat: Include commit id in version reported by CLI

crates/axevent/src/flex.rs
I noticed my IDE complaining about duplicate code and realized this is wrong.
=> fix(axevent): Use correct remove key function

crates/acap-build/src/lib.rs, crates/cargo-acap-build/src/cargo_acap.rs
The renaming of test binaries to the file name expected by `acap-build` was accidentally removed in #139.
=> fix(cargo-acap-build): Name test binaries correctly

.devcontainer/Dockerfile
This reduces the size of the final image from 6.3G to 4.4G it speeds it up by about 1 minute in CI (probably even mor on my Ubuntu 22.04 machine where the `chmod` step takes about 5 minutes).
The main improvement comes from not populating `CARGO_HOME` and `RUSTUP_HOME, and `chmod`ing them in separate steps since this caused the files to be included in two layers; the rust toolchain is particularly expensive at over 1G.
=> chore: Merge some `RUN` steps in `Dockerfile`

bin/remote-test.sh
Use `#!/bin/bash` instead of `#!/bin/sh` to enable use of `-v` option for checking of `AXIS_DEVICE_IP` is set.
- Fixes #165
=> Use `bash` instead of `sh` to enable use of -v comparison operation.

README.md
The large size of Rust binaries is a well known problem and search engines will readily return many results on the topic, not least the excellent min-sized-rust. However, none of these results focus specifically on use cases that are similar to ACAP apps; the three clusters I have observed are:
- code golf: impressive yet impractical exercises in making toy programs as small as possible.
- embedded: true embedded systems with hard limits on space on the order of hundreds of kilobytes.
- WASM
=> chore: Link to article "Managing the size of Rust binaries"

.github/workflows/CI.yml, Makefile
Because `check_miri` started failing:
>    Doc-tests ffi_patterns
> fatal error: cross-interpreting doctests is not currently supported by Miri.
> error: doctest failed, to rerun pass `-p ffi_patterns --doc`
This seems to work for now, but I have a vague memory of pinned nightlies stopping working for me in the past. If this happens we should consider disabling the failing test in CI.
=> chore: Pin nightly

README.md
The command _"$ cargo-acap-build -- -p hello_world"_ builds EAPs for both architectures which is useful since developers might use different devices and don't need to modify the build command for their specific setup.  I have also noticed that it takes less time(approximately 1 sec less) than '_make build AXIS_PACKAGE=hello_world'_.
=> Update build command in root README

apps/bounding_box_example/src/main.rs, apps/embedded_web_page/src/main.rs, apps/inspect_env/src/main.rs, apps/reverse_proxy/src/main.rs, apps/using_a_build_script/src/main.rs, apps/vapix_access/src/main.rs, crates/axevent-sys/build.rs, crates/axevent-sys/src/lib.rs, crates/axoverlay-sys/build.rs, crates/axoverlay-sys/src/lib.rs, crates/axparameter-sys/build.rs, crates/axparameter-sys/src/lib.rs, crates/axstorage-sys/build.rs, crates/axstorage-sys/src/lib.rs, crates/bbox-sys/build.rs, crates/bbox-sys/src/lib.rs, crates/larod-sys/build.rs, crates/larod-sys/src/lib.rs, crates/licensekey-sys/build.rs, crates/licensekey-sys/src/lib.rs, crates/licensekey/src/flex.rs, crates/mdb-sys/build.rs, crates/mdb-sys/src/lib.rs, crates/vdo-sys/build.rs, crates/vdo-sys/src/lib.rs
This improves the experience of working on the project, and any project that depends on the binding crates, on an Apple computer with apple silicon. Getting the bindings to compile is still difficult, but this allows running `cargo check` on host. It may also be necessary to enable working on the other packages on host, but I have not explicitly tested that.
The implementation to this commit does not solve the root problem; if someone is trying to develop of an ARM based computer it is unlikely that we will be able to use the `target_*` keys to classify that as host. But in terms of classification it is a strict improvement over status quo.
=> fix(*): Treat MacOS on ARM as host, not target

apps-aarch64.checksum, apps/challenge_build_tools/manifest.json
I'm not sure if this parameter ever worked, but it does not as of 12.5.56. These are the rules for a valid parameter name:
- Match the regex `[A-Za-z][A-Za-z0-9_]*`
- Have length no more than 32 characters.
The new name is exactly 32 characters and uses all the allowed characters.
Tested on AXIS OS 12.5.56 running on an AXIS M1075-L Box Camera:
- The application can be installed without triggering any errors.
=> fix(challenge_build_tools): Use valid parameter name
